notifications:
  email: false
language:
- cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - gcc-5
    - g++-5
install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-5"; fi
- git clone https://github.com/SFML/SFML.git
- cd SFML
- curl https://gitlab.peach-bun.com/pinion/SFML/commit/3383b4a472f0bd16a8161fb8760cd3e6333f1782.patch | patch -p1
- mkdir build
- cd build
- cmake ..
- make
- sudo make install
- cd ../../
script:
- mkdir install
- mkdir instll/SFMLengine
- cd install/SFMLengine
- cmake -DSFML_DIR=../SFML/build
- make
- sudo make install
